/**
 * Shared seed data for development (populateDatabase.js) and production (seedProductionQuestions.js).
 * Single source of truth for topic names and question content.
 */

/** Topic names per course template (index matches dev courses: COSC 211, COSC 121, STUDY1, STUDY3, STUDY2, STUDY4, STUDY5) */
export const TOPIC_NAMES_BY_TEMPLATE = [
  ['Instruction Set Architectures', 'Pipeline Design', 'Cache Coherence Strategies', 'Memory Hierarchy', 'Parallel Execution Models', 'Performance Benchmarking', 'Other'],
  ['Object-Oriented Design', 'Data Structures Fundamentals', 'Algorithm Analysis', 'Testing and Debugging', 'File I/O and Persistence', 'Recursion Patterns', 'Other'],
  ['Probability', 'Random Variables', 'Expectation', 'Other'],
  ['Logic and proofs', 'Graph theory', 'Other'],
  ['Introduction', 'Human brain', 'Social learning', 'Other'],
  ['Determinants of Health & Health‑Equity', 'Trauma', 'Health promotion', 'Other'],
  ['Research design', 'Data collection and analysis', 'Ethics in research', 'Other']
];

/** 5 questions per template: { description, type, topicIndex, questionText, answer, choices?, correctAnswer? } */
export const SEED_QUESTIONS_BY_TEMPLATE = [
  // Template 0: Machine Architecture (COSC 211)
  [
    { description: 'RISC vs CISC instruction sets', type: 'SA', topicIndex: 0, questionText: 'What is the main difference between RISC and CISC instruction set architectures? Give one advantage of each.', answer: 'RISC uses a small, fixed set of simple instructions and relies on load-store design; CISC uses complex, variable-length instructions that can perform multiple operations. RISC advantages: simpler pipelining, lower power. CISC advantages: denser code, fewer instructions per program.' },
    { description: 'Pipeline hazards and forwarding', type: 'LA', topicIndex: 1, questionText: 'Explain pipeline hazards (data and control). How does data forwarding reduce stalls in a pipeline?', answer: 'Data hazards occur when an instruction needs a result not yet written back. Control hazards occur on branches. Data forwarding (bypassing) sends results from later pipeline stages back to earlier stages so dependent instructions can proceed without waiting for write-back, reducing stalls.' },
    { description: 'TLB and virtual memory', type: 'MCQ', topicIndex: 3, questionText: 'What is the role of the TLB (Translation Lookaside Buffer) in virtual memory?', answer: 'B', choices: [{ letter: 'A', text: 'It stores the full page table' }, { letter: 'B', text: 'It caches recent virtual-to-physical address translations to speed up memory access' }, { letter: 'C', text: 'It replaces the page table' }, { letter: 'D', text: 'It holds swapped-out pages' }], correctAnswer: 'B' },
    { description: 'Pipeline depth trade-offs', type: 'MCQ', topicIndex: 1, questionText: 'What is a drawback of making a pipeline very deep (many stages)?', answer: 'C', choices: [{ letter: 'A', text: 'Clock frequency must decrease' }, { letter: 'B', text: 'Instruction-level parallelism is reduced' }, { letter: 'C', text: 'Branch mispredictions become more expensive' }, { letter: 'D', text: 'Structural hazards are eliminated' }], correctAnswer: 'C' },
    { description: 'Cache hit rate and performance', type: 'MCQ', topicIndex: 3, questionText: 'Which change is most likely to increase cache hit rate?', answer: 'A', choices: [{ letter: 'A', text: 'Increasing temporal and spatial locality in the program' }, { letter: 'B', text: 'Reducing cache size' }, { letter: 'C', text: 'Randomizing memory accesses' }, { letter: 'D', text: 'Disabling write-back caching' }], correctAnswer: 'A' }
  ],
  // Template 1: Computer Programming II (COSC 121)
  [
    { description: 'Arrays vs linked lists', type: 'SA', topicIndex: 1, questionText: 'Compare arrays and linked lists. When would you choose a linked list over an array?', answer: 'Arrays offer O(1) access by index and contiguous memory; linked lists allow O(1) insert/delete at head and dynamic size without reallocation. Choose a linked list when insertions/deletions are frequent and random access by index is not the main operation.' },
    { description: 'Recursion and binary search', type: 'SA', topicIndex: 5, questionText: 'Write or describe a recursive implementation of binary search. What is the base case?', answer: 'Base case: when the search range is empty (low > high) return not found, or when the middle element equals the target return its index. Recursive case: compare target to middle; recurse on left or right half accordingly. Time complexity O(log n).' },
    { description: 'Unit testing and TDD', type: 'MCQ', topicIndex: 3, questionText: 'In test-driven development (TDD), when do you write the unit tests?', answer: 'B', choices: [{ letter: 'A', text: 'After the code is complete' }, { letter: 'B', text: 'Before writing the implementation code' }, { letter: 'C', text: 'Only for bug fixes' }, { letter: 'D', text: 'Only for public methods' }], correctAnswer: 'B' },
    { description: 'Time complexity of operations', type: 'MCQ', topicIndex: 2, questionText: 'What is the average time complexity of searching an unsorted array of n elements?', answer: 'C', choices: [{ letter: 'A', text: 'O(1)' }, { letter: 'B', text: 'O(log n)' }, { letter: 'C', text: 'O(n)' }, { letter: 'D', text: 'O(n log n)' }], correctAnswer: 'C' },
    { description: 'Exception handling semantics', type: 'MCQ', topicIndex: 3, questionText: 'In most languages, what happens to code after a thrown exception that is not caught in the same function?', answer: 'D', choices: [{ letter: 'A', text: 'It continues executing normally' }, { letter: 'B', text: 'It is skipped but local variables remain valid' }, { letter: 'C', text: 'Only finally blocks run; the rest continues' }, { letter: 'D', text: 'It is skipped and control jumps to the nearest matching catch handler up the call stack' }], correctAnswer: 'D' }
  ],
  // Template 2: Introduction to Statistics (STUDY1)
  [
    { description: 'Interpreting the p-value', type: 'SA', topicIndex: 0, questionText: 'In hypothesis testing, how do you interpret a p-value of 0.03? Should you reject the null hypothesis at significance level 0.05?', answer: 'The p-value is the probability of observing the sample data (or more extreme) if the null hypothesis is true. A p-value of 0.03 means there is a 3% chance of such a result under the null. At α = 0.05, we reject the null hypothesis because p < α.' },
    { description: 'Mean vs median for skewed data', type: 'SA', topicIndex: 1, questionText: 'Why might the median be preferred over the mean when describing the center of a skewed distribution?', answer: 'The mean is pulled in the direction of the skew by extreme values; the median is resistant to outliers and better represents the typical value in a skewed distribution.' },
    { description: 'Central limit theorem', type: 'MCQ', topicIndex: 2, questionText: 'What does the Central Limit Theorem state?', answer: 'C', choices: [{ letter: 'A', text: 'All distributions are normal' }, { letter: 'B', text: 'The sample mean approaches the population mean as n increases' }, { letter: 'C', text: 'The sampling distribution of the sample mean approaches a normal distribution as n increases, regardless of the population distribution' }, { letter: 'D', text: 'Standard deviation decreases with sample size only for normal populations' }], correctAnswer: 'C' },
    { description: 'Law of large numbers', type: 'MCQ', topicIndex: 0, questionText: 'What does the Law of Large Numbers say about sample means?', answer: 'B', choices: [{ letter: 'A', text: 'They always equal the population mean for any sample size' }, { letter: 'B', text: 'They converge to the population mean as sample size increases' }, { letter: 'C', text: 'They become more variable as sample size increases' }, { letter: 'D', text: 'They are unrelated to the population mean' }], correctAnswer: 'B' },
    { description: 'Interpreting confidence intervals', type: 'MCQ', topicIndex: 2, questionText: 'A 95% confidence interval for a mean is (10, 14). Which is the best interpretation?', answer: 'A', choices: [{ letter: 'A', text: 'In repeated samples, 95% of such intervals would contain the true population mean' }, { letter: 'B', text: 'There is a 95% chance that the sample mean is between 10 and 14' }, { letter: 'C', text: 'The probability that the true mean is exactly 12 is 95%' }, { letter: 'D', text: '95% of individual observations fall between 10 and 14' }], correctAnswer: 'A' }
  ],
  // Template 3: Discrete Math (STUDY3)
  [
    { description: 'Direct proof and contrapositive', type: 'SA', topicIndex: 0, questionText: 'Prove: If n² is even, then n is even. Use either a direct proof or proof by contrapositive.', answer: 'Proof by contrapositive: Assume n is odd. Then n = 2k + 1 for some integer k. So n² = 4k² + 4k + 1 = 2(2k² + 2k) + 1, which is odd. So if n is odd then n² is odd; equivalently, if n² is even then n is even.' },
    { description: 'Handshaking lemma', type: 'SA', topicIndex: 1, questionText: 'State the handshaking lemma for a graph. Use it to explain why a graph cannot have an odd number of vertices of odd degree.', answer: 'Handshaking lemma: The sum of all vertex degrees equals twice the number of edges. So the sum of degrees is even. If we had an odd number of odd-degree vertices, the sum of their degrees would be odd, and adding even-degree vertices keeps it odd—contradiction. So the number of odd-degree vertices must be even.' },
    { description: 'Euler circuit', type: 'MCQ', topicIndex: 1, questionText: 'When does a graph have an Euler circuit?', answer: 'B', choices: [{ letter: 'A', text: 'When it is connected' }, { letter: 'B', text: 'When every vertex has even degree and the graph is connected' }, { letter: 'C', text: 'When it has no odd-degree vertices' }, { letter: 'D', text: 'When it is a complete graph' }], correctAnswer: 'B' },
    { description: 'Tree properties', type: 'MCQ', topicIndex: 0, questionText: 'Which statement is true for any finite tree with n vertices?', answer: 'C', choices: [{ letter: 'A', text: 'It has exactly n edges' }, { letter: 'B', text: 'It has at most n - 2 edges' }, { letter: 'C', text: 'It has exactly n - 1 edges' }, { letter: 'D', text: 'It must be complete' }], correctAnswer: 'C' },
    { description: 'Graph connectivity', type: 'MCQ', topicIndex: 1, questionText: 'A connected graph with no cycles is called:', answer: 'A', choices: [{ letter: 'A', text: 'A tree' }, { letter: 'B', text: 'A clique' }, { letter: 'C', text: 'A bipartite graph' }, { letter: 'D', text: 'A multigraph' }], correctAnswer: 'A' }
  ],
  // Template 4: Introduction to Psychology (STUDY2)
  [
    { description: 'Brain structures and function', type: 'SA', topicIndex: 1, questionText: 'Name three major structures of the human brain and briefly state one function of each.', answer: 'E.g. Frontal lobe: executive function, planning, decision-making. Hippocampus: formation of long-term memories. Amygdala: emotion processing, especially fear. (Other valid: cerebellum—motor control; occipital lobe—vision; etc.)' },
    { description: 'Classical vs operant conditioning', type: 'SA', topicIndex: 0, questionText: 'How does classical conditioning differ from operant conditioning? Give a brief example of each.', answer: 'Classical conditioning pairs a neutral stimulus with an unconditioned stimulus to produce a learned response (e.g. Pavlov\'s dog salivating to a bell). Operant conditioning strengthens or weakens behavior by consequences—reinforcement or punishment (e.g. a rat pressing a lever for food).' },
    { description: 'Bandura and social learning', type: 'MCQ', topicIndex: 2, questionText: 'According to Bandura\'s social learning theory, learning can occur through:', answer: 'B', choices: [{ letter: 'A', text: 'Reinforcement only' }, { letter: 'B', text: 'Observation and imitation of others, without direct reinforcement' }, { letter: 'C', text: 'Classical conditioning only' }, { letter: 'D', text: 'Biological maturation only' }], correctAnswer: 'B' },
    { description: 'Stages of sleep', type: 'MCQ', topicIndex: 1, questionText: 'Which stage of sleep is most closely associated with vivid dreaming?', answer: 'D', choices: [{ letter: 'A', text: 'Stage 1 (light sleep)' }, { letter: 'B', text: 'Stage 2 (spindle stage)' }, { letter: 'C', text: 'Stage 3 (slow-wave sleep)' }, { letter: 'D', text: 'REM sleep' }], correctAnswer: 'D' },
    { description: 'Types of reinforcement', type: 'MCQ', topicIndex: 2, questionText: 'Giving a child a sticker every time they complete homework is an example of:', answer: 'A', choices: [{ letter: 'A', text: 'Positive reinforcement' }, { letter: 'B', text: 'Negative reinforcement' }, { letter: 'C', text: 'Positive punishment' }, { letter: 'D', text: 'Negative punishment' }], correctAnswer: 'A' }
  ],
  // Template 5: Introduction to Nursing (STUDY4)
  [
    { description: 'Clinical assessment and vital signs', type: 'SA', topicIndex: 1, questionText: 'List the main steps of a basic clinical assessment. Why are vital signs (e.g. temperature, pulse, blood pressure) important in this process?', answer: 'Steps typically include: health history, physical examination, vital signs, and documentation. Vital signs provide objective data on current physiological state and help identify instability, response to treatment, or need for escalation.' },
    { description: 'Patient safety and medication', type: 'SA', topicIndex: 0, questionText: 'Describe at least two principles of patient safety that apply during medication administration.', answer: 'E.g. Right patient, right drug, right dose, right route, right time (five rights); checking allergies; double-checking high-alert medications; clear documentation; patient education about the medication.' },
    { description: 'Health promotion role', type: 'MCQ', topicIndex: 2, questionText: 'Which best describes the nurse\'s role in health promotion?', answer: 'B', choices: [{ letter: 'A', text: 'Only treating acute illness' }, { letter: 'B', text: 'Educating and supporting patients to adopt healthy behaviors and prevent disease' }, { letter: 'C', text: 'Prescribing medications only' }, { letter: 'D', text: 'Replacing the physician in primary care' }], correctAnswer: 'B' },
    { description: 'Standard precautions', type: 'MCQ', topicIndex: 0, questionText: 'Standard precautions (e.g. hand hygiene, gloves) are applied to:', answer: 'C', choices: [{ letter: 'A', text: 'Only patients with known infections' }, { letter: 'B', text: 'Only high-risk procedures' }, { letter: 'C', text: 'All patients, regardless of diagnosis' }, { letter: 'D', text: 'Only patients in isolation rooms' }], correctAnswer: 'C' },
    { description: 'Therapeutic communication', type: 'MCQ', topicIndex: 2, questionText: 'Which nursing action best demonstrates therapeutic communication with a patient who is anxious?', answer: 'D', choices: [{ letter: 'A', text: 'Changing the subject to distract the patient' }, { letter: 'B', text: 'Giving advice and telling the patient what to do' }, { letter: 'C', text: 'Explaining that their feelings are not realistic and should stop' }, { letter: 'D', text: 'Using open-ended questions and active listening' }], correctAnswer: 'D' }
  ],
  // Template 6: Scientific Research Methods (STUDY5)
  [
    { description: 'Qualitative vs quantitative design', type: 'SA', topicIndex: 0, questionText: 'What is the main difference between qualitative and quantitative research design? When might a researcher choose a qualitative approach?', answer: 'Quantitative research uses numerical data and statistical analysis; qualitative research uses non-numerical data (e.g. interviews, text) and thematic analysis. Choose qualitative when exploring meanings, context, or when little is known and the goal is to generate hypotheses or understand experience in depth.' },
    { description: 'Informed consent in research', type: 'SA', topicIndex: 2, questionText: 'What must be ensured to obtain valid informed consent from research participants?', answer: 'Participants must be given clear information about the purpose, procedures, risks, benefits, and right to withdraw; they must understand this information and consent voluntarily without coercion; consent should be documented (e.g. signed form) and the process ongoing, not one-time.' },
    { description: 'Reliability and validity', type: 'MCQ', topicIndex: 1, questionText: 'Why are reliability and validity important in data collection?', answer: 'B', choices: [{ letter: 'A', text: 'They are only important in qualitative research' }, { letter: 'B', text: 'Reliability ensures consistency of measurement; validity ensures we are measuring what we intend to measure' }, { letter: 'C', text: 'They are the same concept' }, { letter: 'D', text: 'They only matter in experiments' }], correctAnswer: 'B' },
    { description: 'Sampling methods', type: 'MCQ', topicIndex: 1, questionText: 'Which sampling method gives every member of the population an equal chance of being selected?', answer: 'A', choices: [{ letter: 'A', text: 'Simple random sampling' }, { letter: 'B', text: 'Convenience sampling' }, { letter: 'C', text: 'Purposive sampling' }, { letter: 'D', text: 'Snowball sampling' }], correctAnswer: 'A' },
    { description: 'Control groups', type: 'MCQ', topicIndex: 0, questionText: 'The main purpose of a control group in an experiment is to:', answer: 'C', choices: [{ letter: 'A', text: 'Increase sample size without cost' }, { letter: 'B', text: 'Guarantee randomization' }, { letter: 'C', text: 'Provide a baseline for comparison with the treatment group' }, { letter: 'D', text: 'Eliminate the need for replication' }], correctAnswer: 'C' }
  ]
];
